### PR TITLE
1kG notebook examples

### PR DESCRIPTION
**Pull request by amygdala**
The   `GWAS_experiments.ipynb` notebook is an update of [this notebook of Nicole's from several years ago](https://github.com/googlegenomics/datalab-examples/blob/master/datalab/genomics/Genome-wide%20association%20study%20(GWAS).ipynb)
It updates for a newer dataset & schema, and google sql rather than 'legacy' sql.
(I left one **TODO** in the nb on purpose.)

The `1kg_analysis.ipynb` notebook is from https://github.com/va-big-data-genomics, and is a good R-based example of 1kG analysis.

### CODE REVIEW

**Comment by amygdala** [comment]
I'm hoping this could be used for 23 & me demos (if useful) later this week.

**Comment by amygdala** [comment]
I've added another notebook to this directory as well, `1kg_analysis.ipynb`.  It is from https://github.com/va-big-data-genomics/variant-analysis-on-bigquery/blob/main/1000g_Analysis.ipynb. I added a bit of VWB intro & tooling at the top but nothing else (so no need to review the meat of the notebook content).

**Review by wnojopra — APPROVED** [review]
I did not run the notebooks, but I loaded them on my cloud environment and confirmed:
1) Links worked properly
2) Documentation read correctly
3) Glance through code shows nothing obviously wrong

**Comment by amygdala** [comment]
thank you, @wnojopra !

**Pull request merged**
